# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - '*'
#- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  jdkVersion: '1.11'
  jarName: 'ado-pipeline-simple-java-app-0.0.1-SNAPSHOT.jar'

stages:
- stage: 'Pre_Build'
  jobs:
  - job: 'Validate'
    steps:
    - task: SonarCloudPrepare@1     # Runs only for PullRequest to Master Branch and Merge to Master
      displayName: 'Prepare analysis on SonarCloud'
      condition: |
        and
        (
          succeeded(),
          or
          (
            eq(variables['Build.SourceBranch'], 'refs/heads/master'),
            eq(variables['System.PullRequest.TargetBranch'], 'master')  
          )
        )
      inputs:
        SonarCloud: 'SonarCloud connection'
        organization: 'sankarav-ado-repo'
        scannerMode: Other
    - task: Maven@3
      displayName: 'Execute Maven goal'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(jdkVersion)'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
        goals: 'verify'
        codeCoverageToolOption: JaCoCo
    - task: SonarCloudPublish@1     # Runs only for PullRequest to Master Branch and Merge to Master
      condition: |
        and
        (
          succeeded(),
          or
          (
            eq(variables['Build.SourceBranch'], 'refs/heads/master'),
            eq(variables['System.PullRequest.TargetBranch'], 'master')  
          )
        )
      displayName: 'Publish Quality Gate Result'
      inputs:
        pollingTimeoutSec: '300'
    
    - script: |
        echo 'Build.SourceBranch = ' $(Build.SourceBranch)
        echo 'Build.Reason = ' $(Build.Reason)
        echo 'System.PullRequest.TargetBranch = ' $(System.PullRequest.TargetBranch)
      displayName: 'Play Ground'

- stage: 'Build' # Runs only for Merge to Master Branch
  jobs:
  - job: 'BuildPublishJar'
    displayName: 'Build & Publish Jar'
    condition: |
      and
      (
        succeeded(),
        eq(variables['Build.SourceBranch'], 'refs/heads/master')
      )
    steps:
    - task: Maven@3
      displayName: 'Build Jar File'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(jdkVersion)'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        # testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
        # codeCoverageToolOption: JaCoCo
    
    # Not sure but reportgenerator is unavailable in MS hosted agent
    # - script: |
    #     reportgenerator -reports:$(Build.SourcesDirectory)/**/jacoco.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:HtmlInline_AzurePipelines
    #   displayName: 'Create code coverage report'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Jar File'
      inputs:
        PathtoPublish: 'target/$(jarName)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - script: |
        echo 'Build.SourceBranch = ' $(Build.SourceBranch)
        echo 'Build.Reason = ' $(Build.Reason)
        echo 'System.PullRequest.TargetBranch = ' $(System.PullRequest.TargetBranch)
      displayName: 'Play Ground'


